In [2]:
import numpy as np

In [3]:
# Escalar is a value like a number
scalar = np.array(42)
scalar.ndim

0

In [4]:
# Vector is a data structure with one dimension 
vector = np.array([1,2,3])
vector.ndim

1

In [5]:
# Matriz is a data structure with two dimensions
matriz = np.array([[1,2], [3,4]])
matriz.ndim

2

In [6]:
# Tensor is a data structure with more than two dimensions
tensor = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[9,8,7], [6,5,4], [3,2,1]]])
tensor.ndim

3

In [7]:
# Add dimensions
vector_dimensionado = np.array([1,2,3], ndmin=10)       # Add the dimensions that assign in ndmin
print(vector_dimensionado)
vector_dimensionado.ndim

# Delete dimensions
vector_dimensionado2 = np.squeeze(vector_dimensionado)  # Delete the dimensions that wasn't used
print(vector_dimensionado2)                            
vector_dimensionado2.ndim                               # 1

[[[[[[[[[[1 2 3]]]]]]]]]]
[1 2 3]


1

In [9]:
expand = np.expand_dims(np.array([1,2,3]), axis=0)      # Add a new dimension in the rows(0) and columns(1)
print(expand)
expand.ndim

[[1 2 3]]


2