In [2]:
import numpy as np

In [3]:
# Create array using python syntax

lista_py = list(range(0,10))
array_from_py = np.array(lista_py)
array_from_py

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Create array using numpy sintax

array_from_np = np.arange(0,21, 5, dtype='int64')
array_from_np

array([ 0,  5, 10, 15, 20])

In [5]:
# Create array with full zeros

zero_array = np.zeros(10)
print(zero_array)
zero_array = np.zeros([10, 5])
print(zero_array)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
# Create array with full ones

one_array = np.ones(10)
print(one_array)
one_array = np.ones([10, 5])
print(one_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
# Create an array with 400 values between 0 and 10

range_arr = np.linspace(0, 10, 400)
range_arr

array([ 0.        ,  0.02506266,  0.05012531,  0.07518797,  0.10025063,
        0.12531328,  0.15037594,  0.1754386 ,  0.20050125,  0.22556391,
        0.25062657,  0.27568922,  0.30075188,  0.32581454,  0.35087719,
        0.37593985,  0.40100251,  0.42606516,  0.45112782,  0.47619048,
        0.50125313,  0.52631579,  0.55137845,  0.5764411 ,  0.60150376,
        0.62656642,  0.65162907,  0.67669173,  0.70175439,  0.72681704,
        0.7518797 ,  0.77694236,  0.80200501,  0.82706767,  0.85213033,
        0.87719298,  0.90225564,  0.9273183 ,  0.95238095,  0.97744361,
        1.00250627,  1.02756892,  1.05263158,  1.07769424,  1.10275689,
        1.12781955,  1.15288221,  1.17794486,  1.20300752,  1.22807018,
        1.25313283,  1.27819549,  1.30325815,  1.3283208 ,  1.35338346,
        1.37844612,  1.40350877,  1.42857143,  1.45363409,  1.47869674,
        1.5037594 ,  1.52882206,  1.55388471,  1.57894737,  1.60401003,
        1.62907268,  1.65413534,  1.67919799,  1.70426065,  1.72

In [11]:
# Create an identity matriz with this dimensions 4 columns and 4 rows

identidad = np.eye(4,4)
identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
# Create a random float (), vector with random float values (n), matriz (n,n), tensor(n,n,n)

np.random.rand()

0.815734689250454

In [19]:
# Create a matrix of (10x10) with values between 1 and 10 
np.random.randint(1,10, (4,4))

array([[4, 8, 2, 5],
       [6, 2, 7, 9],
       [9, 7, 4, 3],
       [6, 7, 4, 8]])