In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10, (3,2))
arr

array([[1, 5],
       [3, 3],
       [4, 3]])

In [3]:
# This function shows the dimensions of the array
arr.shape

(3, 2)

In [4]:
# This function change the dimension of the original array --> The product of values could be the same that original array
arr.reshape(2,3)

array([[1, 5, 3],
       [3, 4, 3]])

In [5]:
# Another possible form of the original array
np.reshape(arr, (1,6))

array([[1, 5, 3, 3, 4, 3]])

In [6]:
np.reshape(arr, (2,3), 'C')     # --> Como lo hace el lenguaje C

array([[1, 5, 3],
       [3, 4, 3]])

In [11]:
np.reshape(arr, (2,3), 'F')     # --> Como lo hace el lenguaje Fortran

array([[1, 4, 3],
       [3, 5, 3]])

In [8]:
np.reshape(arr, (2,3), 'A')     # --> Como lo hace el lenguaje de mi sistema

array([[1, 5, 3],
       [3, 4, 3]])

In [9]:
# Challenge --> Modify shape of a tensor with 24 values 

tensor = np.random.rand(2,3,4)
print(tensor.shape)
print(tensor)

tensor_2 = np.reshape(tensor, (6,2,2), 'F')
print(tensor_2.shape)
print(tensor_2)

(2, 3, 4)
[[[0.44077956 0.90560289 0.20100955 0.01330526]
  [0.08414863 0.93342315 0.79767961 0.15201221]
  [0.86881881 0.40833287 0.65326335 0.52930533]]

 [[0.96753352 0.62964826 0.48616907 0.98695505]
  [0.10192948 0.19112956 0.29723547 0.89275053]
  [0.79132474 0.94597236 0.2161001  0.54892515]]]
(6, 2, 2)
[[[0.44077956 0.20100955]
  [0.90560289 0.01330526]]

 [[0.96753352 0.48616907]
  [0.62964826 0.98695505]]

 [[0.08414863 0.79767961]
  [0.93342315 0.15201221]]

 [[0.10192948 0.29723547]
  [0.19112956 0.89275053]]

 [[0.86881881 0.65326335]
  [0.40833287 0.52930533]]

 [[0.79132474 0.2161001 ]
  [0.94597236 0.54892515]]]
