In [1]:
import numpy as np

In [2]:
# Create random vector with 10 integer values between 1 and 20
arr = np.random.randint(1,20,10)
arr

array([16, 12,  1, 14,  7, 10, 19, 18, 13,  6])

In [3]:
# Reshape vector to transform into a matrix
matriz = np.reshape(arr, (2,5))
matriz

array([[16, 12,  1, 14,  7],
       [10, 19, 18, 13,  6]])

In [4]:
# Max value
arr.max()
matriz.max(1)                # --> If don't specificate return max value, if the value is 0 return max value by column and if the values is 1 return max value by row

# Min value
arr.min()
matriz.min(0)                # --> If don't specificate return min value, if the value is 0 return min value by column and if the values is 1 return min value by row


array([10, 12,  1, 13,  6])

In [5]:
# Indexes

arr.argmax()
matriz.argmax(1)             # --> If don't specificate return index of max value, if the value is 0 return index of max value by column and if the values is 1 return index of max value by row

arr.argmin()
matriz.argmin(0)              # --> If don't specificate return index of min value, if the value is 0 return index of min value by column and if the values is 1 return index of min value by row

array([1, 0, 0, 1, 1])

In [6]:
# Difference between upper and lower value (Peak to Peak)

arr.ptp()
matriz.ptp(1)               # --> If don't specificate the number return the difference beween max value and min value, 0 return by column and 1 return by row

array([15, 13])

In [7]:
# Percentile --> Indicate a key value in total values associated by percentage

per_fifty = np.percentile(arr, 50)
per_fifty

12.5

In [8]:
# Sort to ordenate an array by parameters

arr.sort()
arr

matriz.sort()
matriz

array([[ 1,  6,  7, 10, 12],
       [13, 14, 16, 18, 19]])

In [9]:
# Median to return average value from two continuos values in the middle of an array

np.median(matriz, 0)            # --> 0 by columns 1 by rows

array([ 7. , 10. , 11.5, 14. , 15.5])

In [10]:
# Standar deviation to indicate the dispersion about the values

np.std(arr)
np.std(matriz,0)                # --> 0 by columns 1 by rows

array([6. , 4. , 4.5, 4. , 3.5])

In [11]:
# Varianza is the square of Standar deviation 

varianza = np.std(arr) ** 2         
np.var(arr) 
np.var(matriz)


29.040000000000003

In [12]:
# Average

np.mean(arr)
np.mean(matriz,0)               # --> 0 by columns 1 by rows

array([ 7. , 10. , 11.5, 14. , 15.5])

In [13]:
# Concatenate

a = np.array([[1,2], [1,2]])
b = np.array([5,6])

print(np.shape(a))
print(np.shape(b))

b = np.expand_dims(b, axis=1)               # --> To increase one dimension of an array

np.concatenate((b.T,a), axis=0)             # --> Concatenate two arrays by axis

(2, 2)
(2,)


array([[5, 6],
       [1, 2],
       [1, 2]])