In [2]:
import numpy as np

In [3]:
# Declare the array 
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# Extract by slicing a portion of the original array
slice = arr[0:6]
slice

array([0, 1, 2, 3, 4, 5])

In [5]:
# We make a modification of the original array
slice[:] = 0
slice

print(slice)
print(arr)              # --> We can see that the original array is changed (This is not good at all)

[0 0 0 0 0 0]
[ 0  0  0  0  0  0  6  7  8  9 10]


In [6]:
# Create a copy of an array
arr_copy = np.copy(arr)
arr_copy               # --> numpy has the method copy, to make a copy, assign to a new variable 

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [7]:
arr_copy[:] = 100
arr_copy              # --> We work with another variable with the same values

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [9]:
print('arr --> ', arr)                  # --> [ 0  0  0  0  0  0  6  7  8  9 10]                 --> Doesn't was modified
print('arr_copy --> ', arr_copy)             # --> [100 100 100 100 100 100 100 100 100 100 100]      --> This was modified

arr -->  [ 0  0  0  0  0  0  6  7  8  9 10]
arr_copy -->  [100 100 100 100 100 100 100 100 100 100 100]
