In [8]:
import numpy as np

In [9]:
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [10]:
# Conditional
indices_cond = arr > 5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [11]:
# We apply the condition to make slicing in the array
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [12]:
# Conditional with two conditions to make slicing
arr[(arr > 5) & (arr <9)]

array([6, 7, 8], dtype=int8)

In [13]:
# Conditional to modified values according to a condition
arr[arr > 5] = 99
arr                     # --> We could see that the original array was changed, therefore is good to make a copy

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)