In [1]:
import numpy as np

In [2]:
lista = [1,2]
lista 

[1, 2]

In [3]:
lista * 2           # --> This function duplicate the array and not realize the operation in their inputs (don't succed if is apply in a list)

[1, 2, 1, 2]

In [4]:
arr = np.arange(0,10)
arr2 = arr.copy()
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr2 * 2        # --> Multiply each position by 2. Analogy: arr.map(x => x*2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr2 + 2        # --> Add each position by 2. Analogy: arr.map(x => x+2)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
1 / arr2        # --> Divided 1 by each position of the array. Analogy: arr.map(x => 1/x)

/tmp/ipykernel_3602/4205943980.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr2        # --> Divided 1 by each position of the array. Analogy: arr.map(x => 1/x)


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [8]:
# Add two arrays
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
# Make a copy of a matriz
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()
matriz2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
matriz ** matriz2       # --> Operations between matrix, in this case we elevate the value of the first matrix to value of second matrix

array([[        1,         1,         4,        27,       256],
       [     3125,     46656,    823543,  16777216, 387420489]])

In [17]:
# Matricial product
print('np.matmul', np.matmul(matriz, matriz2.T))
print('np.dot', np.dot(matriz, matriz2.T))
print('@', matriz @ matriz2.T)

print(np.shape(matriz))
print(np.shape(matriz2.T))

[[ 30  80]
 [ 80 255]]
[[ 30  80]
 [ 80 255]]
[[ 30  80]
 [ 80 255]]
