In [17]:
import numpy as np

otra_matriz = np.array([[21, 22, 23, 24], [25, 26, 27, 28], [29, 30, 31, 32], [33, 34, 35, 36]])

resultado1 = otra_matriz[:, 0]                      # Toda la fila 0
resultado2 = otra_matriz[::2, [1, 3]]               # Todas las columnas pares de indices 1 y 3
resultado3 = otra_matriz[::-1, :]                   # Invierte por columnas y trae todas las filas
resultado4 = otra_matriz[otra_matriz <= 30]         # Trae todos los valores menores o iguales a 30
resultado5 = otra_matriz[2:, 2:]                    # Trae la submatriz que inicia en la columna 2 y fila 2 hasta el final
# otra_matriz[otra_matriz > 25] = -1                # Devuelve la misma matriz pero en los valores mayores a 25 escribe -1
# resultado6 = otra_matriz                          
resultado7 = np.fliplr(otra_matriz).diagonal()      # Devuelve la diagonal segundaria ordenada de manera ascendente
resultado8 = otra_matriz[:, -1]                     # Devuelve la última fila completa
resultado9 = otra_matriz[1::2, :]                   # Devuelve las columnas impares completas
resultado10 = otra_matriz[otra_matriz % 2 != 0]     # Devuelve los valores impares de la matriz

print("Resultado 1:", resultado1)
print("Resultado 2:", resultado2)
print("Resultado 3:\n", resultado3)
print("Resultado 4:", resultado4)
print("Resultado 5:\n", resultado5)
# print("Resultado 6:\n", resultado6)
print("Resultado 7:", resultado7)
print("Resultado 8:", resultado8)
print("Resultado 9:\n", resultado9)
print("Resultado 10:", resultado10)

Resultado 1: [21 25 29 33]
Resultado 2: [[22 24]
 [30 32]]
Resultado 3:
 [[33 34 35 36]
 [29 30 31 32]
 [25 26 27 28]
 [21 22 23 24]]
Resultado 4: [21 22 23 24 25 26 27 28 29 30]
Resultado 5:
 [[31 32]
 [35 36]]
Resultado 7: [24 27 30 33]
Resultado 8: [24 28 32 36]
Resultado 9:
 [[21 22 23 24]
 [29 30 31 32]]
Resultado 10: [21 23 25 27 29 31 33 35]
