In [1]:
import numpy as np

In [8]:
mat = [[1,2,3], [4,5,6], [7,8,9]]
matriz = np.array(mat)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
print(matriz[0,0])                              # Primer elemento de la matriz
print(matriz[-1, :])                            # Ultima fila de la matriz  
print(matriz[:, -1])                            # Ultima columna de la matriz
print(matriz[1, :])                             # Toda la fila 2
print(matriz[:, 2])                             # Toda la columna 3
print(matriz.diagonal())                        # Toda la diagonal principal 
print(matriz[::-1].diagonal())                  # Toda la diagonal secundaria
print(matriz[matriz > 5])                       # Todos los valores mayores a 5 de la matriz
print(matriz[matriz <= 3])                      # Todos los valores menores o iguales a 3 de la matriz
print(matriz[(matriz < 6) & (matriz > 2)])      # Todos los valores entre 2 y 6 de la matriz

1
[7 8 9]
[3 6 9]
[4 5 6]
[3 6 9]
[1 5 9]
[7 5 3]
[6 7 8 9]
[1 2 3]
[3 4 5]
